# Generated by Django 3.0.7 on 2023-05-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lasttname', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('facbook_link', models.URLField(max_length=100)),
                ('created_data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
