# Generated by Django 3.0.7 on 2023-05-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='lasttname',
            new_name='lastname',
        ),
    ]
