# Generated by Django 3.0.7 on 2023-05-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20230526_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='google_link',
            field=models.URLField(default='https://www.google.co.in', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(default='https://www.twitter.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='facbook_link',
            field=models.URLField(default='http://www.facebook.com', max_length=100),
        ),
    ]
